const ADD_TODO = 'ADD_TODO';
const UPDATE_TODO = 'UPDATE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const ADD_REDUX_SAUCE_TODO = 'ADD_REDUX_SAUCE_TODO';
const UPDATE_REDUX_SAUCE_TODO = 'UPDATE_REDUX_SAUCE_TODO';
const DELETE_REDUX_SAUCE_TODO = 'DELETE_REDUX_SAUCE_TODO';
const SELECT_REDUCER = 'SELECT_REDUCER';

export {
  ADD_TODO,
  UPDATE_TODO,
  DELETE_TODO,
  ADD_REDUX_SAUCE_TODO,
  UPDATE_REDUX_SAUCE_TODO,
  DELETE_REDUX_SAUCE_TODO,
  SELECT_REDUCER,
};
